spring:
  application:
    name: ybdizaynavize
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ybdizaynavize_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
logging:
  file:
    path: logs/
    name: ybdizaynavize.log
